ekamapp/user/routes.py
import time
from flask import jsonify, render_template,url_for,flash,redirect,request,make_response,session,Blueprint, current_app as app
from ekamapp.user.dao import get_event_by_code, get_user_by_id,save_user
from ekamapp.user.forms import RegistrationForm, StartForm
from ekamapp.models import  User
from ekamapp.utils import check_login_status, generate_qr_code, generate_qr_code_response, generate_unique_referral_link,parse_event_datetime,login_required,get_user_object
from ekamapp.wati_utils import send_ticket, send_verification_message


users = Blueprint('users', __name__)

WEBHOOK_TRIGGERED = False

@users.route('/webhook/transaction', methods=['POST'])
def transaction_webhook():
    global WEBHOOK_TRIGGERED
    data = request.json
    app.logger.info(f"Received webhook data: {data}")

    if data.get('eventType') == 'sentMessageREPLIED':
        WEBHOOK_TRIGGERED = True
        app.logger.info("Webhook triggered successfully")
        return jsonify({'status': 'success'}), 200
    else:
        app.logger.warning("Invalid webhook event type")
        return jsonify({'status': 'failure'}), 400

@users.route('/<string:event_code>', methods=['GET', 'POST'])
def register(event_code):
    app.logger.info(f"Registration attempt for event code: {event_code}")
    if check_login_status():
        app.logger.info("User already logged in. Redirecting to dashboard.")
        return redirect(url_for('users.dashboard'))
    
    global WEBHOOK_TRIGGERED
    referrer = request.args.get('referrer') or request.form.get('referrer')
    if referrer:
        session['referrer'] = referrer
    else:
        referrer = session.get('referrer')
    
    event = get_event_by_code(event_code)
    event_d = parse_event_datetime(event)
    form = RegistrationForm()
    
    if form.validate_on_submit():
        app.logger.info(f"Form submitted for user: {form.name.data}")
        user_data = get_user_object(form, referrer)
        app.logger.debug(f"User data: {user_data}")
        
        try:
            phone = user_data['country_code'] + user_data['whatsapp']
            user = User.query.filter_by(whatsapp=phone).first()

            if user:
                app.logger.info(f"WhatsApp number already registered: {phone}")
                flash('This WhatsApp number is already registered. Please log in.', 'info')
                return redirect(url_for('users.login', event_code=event_code))
            
            response = send_verification_message(phone, user_data['name'])

            if response == 200:
                app.logger.info(f"Verification message sent successfully to: {phone}")
                WEBHOOK_TRIGGERED = False
                start_time = time.time()

                while True:
                    if WEBHOOK_TRIGGERED:
                        user = save_user(user_data, event)
                        app.logger.info(f"User saved successfully: {user.id}")
                        QRcode = generate_qr_code(user, event)
                        send_ticket(user.name, user.whatsapp, event)
                        flash("Your ticket has been sent to your WhatsApp. Please check")
                        response = make_response(redirect(url_for('users.dashboard')))
                        response.set_cookie('user_id', str(user.id))
                        response.set_cookie('user_name', user.name)
                        response.set_cookie('event_code', event.event_code)
                        session['phone'] = phone
                        flash(f'Congrats, {form.name.data}! You are now registered for Ekam E2!', 'success')
                        flash("Ticket details have been sent to your registered WhatsApp. Please check your WhatsApp.")
                        return response

                    if time.time() - start_time >= 120:
                        app.logger.warning(f"Webhook timeout for user: {user_data['name']}")
                        flash("You haven't responded to our WhatsApp verification. Please try again.", 'danger')
                        return redirect(url_for('users.register', event_code=event_code))

                    time.sleep(1)

            else:
                app.logger.error(f"WhatsApp authentication failed for: {phone}")
                flash("Your WhatsApp authentication has failed. Please try again.", 'danger')
                return render_template('registration_index.html', event=event_d, form=form, title='Register')

        except ValueError as ve:
            app.logger.error(f"ValueError during registration: {str(ve)}")
            flash(str(ve), 'danger')
        except Exception as e:
            app.logger.exception(f"Unexpected error during registration: {str(e)}")
            flash("An error occurred during registration. Please try again later.", 'danger')

    return render_template('registration_index.html', event=event_d, form=form, title='Register')

@login_required
@users.route("/dashboard", methods=['GET', 'POST'])
def dashboard():

    event_obj=parse_event_datetime(get_event_by_code(request.cookies.get('event_code')))
    if request.cookies.get('user_id'):
        
        user_info=get_user_by_id(request.cookies.get('user_id'))
        referral_link=generate_unique_referral_link(user_info,user_info.events[0])
        if user_info:
            registered_event = user_info.events[0]  # Get all events the user has registered for
            event_qr_code =  generate_qr_code_response(user_info, registered_event)
        else:
            registered_event = None
            event_qr_code = None
                # Fetch upcoming events
        
            # Get IDs of registered events
        #registered_event_ids = [event.id for event in registered_events]

            # Query upcoming events excluding already registered ones
        #upcoming_events = get_upcoming_events(registered_event_ids)
        #print(registered_events)
        return render_template('dashboard.html',user=user_info,event= parse_event_datetime(user_info.events[0]),event_qr_code=event_qr_code,referral_link=referral_link,cookies=True)
    else:
        form =RegistrationForm()

        return render_template('registration_index.html',event=event_obj, form=form, title='Register',cookies=False)
    



@users.route("/logout", methods=['GET', 'POST'])
def logout():
    event_obj=parse_event_datetime(get_event_by_code(request.cookies.get('event_code')))   
    response = make_response(redirect(url_for('users.login',event_code=event_obj["event_code"])))
    response.set_cookie('user_id', '', expires=0)
    response.set_cookie('user_name', '', expires=0)
    response.set_cookie('event_code', '', expires=0)

        # Add headers to prevent caching
    response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    session.clear()
    return response

@users.route("/login/<string:event_code>", methods=['GET', 'POST'])
def login(event_code):
    global WEBHOOK_TRIGGERED
    event=get_event_by_code(event_code)
    event_d=parse_event_datetime(event)
    form =StartForm()
    if form.validate_on_submit():
 
            user_data = {
  
                "country_code":form.country_code.data,
                "whatsapp": form.whatsapp.data,
            }
 
            phone=user_data['country_code'][1:]+user_data['whatsapp']
            user = User.query.filter_by(whatsapp=phone).first()
            if user:
                response = send_verification_message(phone, user.name)
                if response == 200:
                    WEBHOOK_TRIGGERED = False
                    session['phone'] = phone
                    start_time = time.time()
                    
                    while True:
                        if WEBHOOK_TRIGGERED:
                            response = make_response(redirect(url_for('users.dashboard')))
                            response.set_cookie('user_id', str(user.id))
                            response.set_cookie('user_name', user.name)
                            response.set_cookie('event_code', event.event_code)
                            return response

                        # Check if 2 minutes have passed
                        if time.time() - start_time >= 120:  # 2 minutes in seconds
                            flash("You haven't responded to our WhatsApp verification. Please try again.", 'danger')
                            return redirect(url_for('users.register', event_code=event_code))

                        time.sleep(1)  # Sleep for 1 second before checking again

                else:
                    flash("Your WhatsApp authentication has failed. Please try again.", 'danger')
                    return render_template('registration_index.html', event=event_d, form=form, title='Register')



    return render_template('lgn_index.html',form=form,event=event_d)

ekamapp/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="css/dashboard.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
        <script src="{{ url_for('static', filename='js/home_script.js') }}"></script>
    </head>

    <body>
        <div class="dashboard_container">
            <div class="drawer_overlay" id="drawerOverlay" onclick="drawerToogle()"></div>
            <div class="drawer" id="drawer">
                <div class="drawer_logo">
                    <img src="../static/img/combo_logo.png" alt="">
                </div>
                <div class="user_logo">
                    <img src="../static/img/user_ico.png" alt=""> {{user.name}}
                </div>

                <div class="nav_links">
                    Profile
                </div>

                <div class="nav_links">
                    My Referrals
                </div>

                <div class="qr_link">
                    <div class="qr_img">
                        <img src="../static/img/qr_ico.svg" alt="" srcset="">
                    </div>
                    <div class="mt10">
                        Your Personal Invite <br> QR Code
                    </div>
                    <button>Download QR Code</button>
                </div>

                <div class="logout">
                    <form action="{{ url_for('users.logout') }}" method="post">
                        <button type="submit" class="btn btn-link">
                            <img src="../static/img/logout_ico.svg" alt="Logout Icon"> Logout
                        </button>
                    </form>
                </div>
                
                
            </div>
            <div class="dashboard-content">
                <div class="nav_bar flex alc spb">
                    <div class="nav_logo">
                        <img src="../static/img/combo_logo.png" alt="">
                    </div>
                    <div class="nav_toogle" onclick="drawerToogle()">
                        <img src="../static/img/TabBar-Icons.svg" alt="" srcset="">
                    </div>
                </div>
                <div class="dashboard_main">
                    <div class="event_section">
                        <div class="flex alc spb">
                            <div>
                                Upcoming
                            </div>
                            <div class="flex alc spb guru_tab">
                                <div class="flex alc guru_ico">
                                    <img src="../static/img/guru_ico.svg" alt="" srcset="">
                                </div>
                                <div>Mukti Guru Sri Krishnaji</div>
                            </div>
                        </div>

                        <div class="event_banner">
                            <img src="../static/img/event_banner.png" alt="">
                        </div>

                        <div class="event_header">
                            Path to Enlightenment: Awakening the Inner Self
                        </div>

                        <div class="event_body">
                            Join us for "Harmony in Motion: A Yoga Journey for Body and Soul." This rejuvenating yoga session offers gentle stretches, mindful breathing, and meditation for all levels. Experience tranquility and connection, and leave feeling refreshed and inspired.
                        </div>

                        <div class="event_calendar flex alc">
                            <div class="calender mr10">
                                <img src="../static/img/calnd.png" alt="">
                            </div>
                            <div class="mr10" style="border-right: 2px solid #ccc; padding-right: 10px;">
                                {{event.date}} {{event.month}}<br> {{event.year}}
                            </div>
                            <div>
                                9:00 AM
                            </div>
                        </div>

                        <div class="event_venue flex alc">
                            <div class="event_ico">
                                <img src="../static/img/location.png" alt="">
                            </div>
                            <div class="event_loc">
                                <div class="event_loc_head">{{ event.location }}</div>
                                <div class="event_loc_body">{{ event.location }} <br/> {{ event.place }}, Kerala</div>
                            </div>
                        </div>

                        <div class="participate">
                            <div class="fn14 flex alc">
                                <div class="ticket_ico">
                                    <img src="../static/img/ticket_ico.png" alt=""> 
                                </div>
                                How to participate?
                            </div>
                            <div class="mt10">
                                Tickets for "Path to Enlightenment: Awakening the Inner Self" are now available! Secure your spot to embark on this transformative journey. Spaces are limited, so book early to ensure your place.
                            </div>
                        </div>
                    </div>
                    <div class="ticket_section">
                        <div class="entry_ticket">
                            <div class="entry_gold">
                                <div class="fn14 flex alc">
                                    <div class="ticket_ico">
                                        <img src="../static/img/ticket_gold.svg" alt=""> 
                                    </div>
                                    Entry Ticket
                                </div>
                                <div class="flex alc mt10">
                                    <div class="qr_img white_qr">
                                        <img id="qrCodeImg" src="data:image/png;base64,{{ event_qr_code }}" alt="" srcset="">
                                    </div>
                                    <div class="text_center event_btn_content">
                                        <div class="gold_text">Scan this QR Code to access your entry pass</div>
                                        <div class="entry_dwld_btn">
                                            <button id="downloadQrCodeBtn">
                                                <img src="../static/img/download_ico.svg" alt="" srcset=""> Download Entry QR Code
                                            </button>
                                        </div>
                                    </div>
                                </div>                                
                            </div>
                            
                        </div>

                        <div class="flex alc event_group">
                            <div class="group_ico">
                                <img src="../static/img/joim_mem_ico.svg" alt="" srcset="">
                            </div>
                            <div>
                                Join the countless individuals already embarking on their spiritual journey.
                            </div>
                        </div>


                        
                        <div class="click_input">
                            <input type="text" id="referralLink" value="{{referral_link}}">
                            <div class="copy_btn" type="button" onclick="copyReferralLink()">
                                click to copy
                            </div>
                        </div>

                        <div class="flex alc whatsapp mt10">
                            <button class="flex alc mr10">
                                <img src="../static/img/wa_status.svg" alt="" srcset=""> WA Story
                            </button>
                            <button class="flex alc">
                                <img src="../static/img/whatsapp_ico.svg" alt="" srcset=""> Share On Whatsapp
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script>
            let toogle = false
            function drawerToogle(){
                toogle = !toogle;
                if(toogle){
                    document.getElementById('drawer').classList.add('active');
                    document.getElementById('drawerOverlay').style.display = "block";
                }else{
                    document.getElementById('drawer').classList.remove('active');
                    document.getElementById('drawerOverlay').style.display = "none";
                }
            }
            
            function copyReferralLink() {
                    /* Get the text field */
                    var copyText = document.getElementById("referralLink");

                    /* Select the text field */
                    copyText.select();
                    copyText.setSelectionRange(0, 99999); /* For mobile devices */

                    /* Copy the text inside the text field */
                    document.execCommand("copy");

                    /* Alert the user that the text has been copied */
                    alert("Referral link copied to clipboard: " + copyText.value);
                }
        </script>
    </body>

</html>

ekamapp/templates/lgn_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../static/css/style.css">
</head>
<body>
    <section class="home">
        <div class="flex_container">
            <div class="form_section">
                <form  id="startform" class="form" method="post" action="{{ url_for('users.login',event_code=event.event_code) }}">
                    {{ form.hidden_tag() }}
                    <div class="form_head">Start with your Whatsapp number</div>
                    <div class="form_control flex">
                        <div class="form_code">
                            {{ form.country_code(class="form-control custom-select", style="max-width: 5em;") }}
                        </div>
                        <div style="width: 100%;">
                            {% if form.whatsapp.errors %}
                            {{ form.whatsapp(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.whatsapp.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.whatsapp(class="form-control") }}
                            {% endif %}
                            <span id="whatsappError" class="error-message"></span>
                        </div>
                    </div>
                    <button type="submit">GET STARTED</button>

                    <div class="form_details flex">
                        <div class="whats_ico">
                            <img src="../static/img/whatsapp_ico.png" alt="">
                        </div>
                        <div class="form_instructions">
                            <div>Registred numbers will recieve a message on Whatsapp</div>
                            <div style="margin-top: 5px;">
                                <a href="{{ url_for('users.register', event_code=event.event_code) }}">New members? Click here to register</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="details_section">
                <div class="head_logo">
                    <img src="../static/img/oneness_logo.png" alt="" srcset="">
                </div>
                <div class="head_content">
                    <div class="experience">
                        <img src="../static/img/E.png" alt="" srcset="">
                    </div>
                </div>
            </div>
        </div>
        <div class="date_container flex">
            <div style="padding-right: 15px; margin-right: 10px; border-right: 3px solid #000;">
                {{event.date}} {{event.month}}<br> {{event.year}}
            </div>
            <div style="margin-left: 10px;">
                {{event.location}} <br> {{event.place}} 
            </div>
        </div>
        <div class="experience_user">
            <img src="../static/img/guru1.png" alt="">
        </div>

        <div class="form_section_mobile">
            <div class="date_container_mobile flex">
                <div style="padding-right: 15px; margin-right: 10px; border-right: 3px solid #000;">
                    {{event.date}} {{event.month}} <br> {{event.year}}
                </div>
                <div style="margin-left: 10px;">
                    {{event.location}} <br> {{event.place}} 
                </div>
            </div>
            <div class="experience_user_mobile">
                <img src="../static/img/guru1.png" alt="">
            </div>
            <form  id="startform" class="form" method="post" action="{{ url_for('users.login',event_code=event.event_code) }}">
                {{ form.hidden_tag() }}
                <div class="form_head">Start with your Whatsapp number</div>
                <div class="form_control flex">
                    <div class="form_code">
                        {{ form.country_code(class="form-control custom-select", style="max-width: 5em;") }}
                    </div>
                    <div style="width: 100%;">
                        {% if form.whatsapp.errors %}
                        {{ form.whatsapp(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.whatsapp.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.whatsapp(class="form-control") }}
                        {% endif %}
                        <span id="whatsappError" class="error-message"></span>
                    </div>
                </div>
                <button type="submit">GET STARTED</button>

                <div class="form_details flex">
                    <div class="whats_ico">
                        <img src="../static/img/whatsapp_ico.png" alt="">
                    </div>
                    <div class="form_instructions">
                        <div>Registred numbers will recieve a message on Whatsapp</div>
                        <div style="margin-top: 5px;">
                            <a href="{{ url_for('users.register', event_code=event.event_code) }}">New members? Click here to register</a>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </section>
</body>
</html>